sudo mpc add http://mp3channels.webradio.antenne.de:80/antenne
sudo mpc add http://streams.br.de/bayern2_2.m3u
sudo mpc add http://streams.br.de/bayern3_2.m3u
sudo mpc add http://mp3stream1.apasf.apa.at:8000
sudo mpc add http://www.egofm.de/stream/192kb
sudo mpc add http://energyradio.de/muenchen
sudo mpc add http://mp3.webradio.rockantenne.de:80
sudo mpc add http://mp3channels.webradio.rockantenne.de/alternative
sudo mpc add http://mp3channels.webradio.rockantenne.de/heavy-metal
sudo mpc add http://stream.sport1.fm/api/livestream-redirect/SPORT1FM_24_7.mp3
sudo mpc add http://uwstream2.somafm.com:9290
sudo mpc add http://uwstream3.somafm.com:9806
sudo mpc add http://uwstream3.somafm.com:9090
sudo mpc add http://uwstream3.somafm.com:8700
sudo mpc add http://uwstream3.somafm.com:6200
